baseURL = "https://dukefr.github.io/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "Noudel Mark-Andrew"
# Main Menu
[[menu.main]]
name = "Menu"
url = "#home"
weight = 1
[[menu.main]]
name = "A propos de moi"
url = "#about"
weight = 2
[[menu.main]]
name = "Projets"
url = "#portfolio"
weight = 4
[[menu.main]]
name = "Mon CV"
url = "#resume"
weight = 5
[[menu.main]]
name = "Mes Competences"
url = "#skills"
weight = 6

# Sitemap Menu
[[menu.sitemap]]
name = "A propos de moi"
url = "about"
weight = 1


[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © Portio 2020"
footerLogo = "images/contact/widget-logo.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"

[params.address]
email = "mark-andrew.noudel@edu.ece.fr"
phone = "438-624-7424"
address = "Montréal"

[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/"
weight = 2
[[params.social]]
icon = "fa-pinterest-square"
url = "https://www.pinterest.com/"
weight = 3
[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/"
weight = 4
